title: WylHan
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
    Been interested in programming since I learned about it back
when the internet didnt even *exist*    
  

# WyllHan(m.me/wyllhan@facebook.com)
twitter_username: your-twitter-handle
wylhan: wylhan@github.com

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-minima
theme: jekyll-theme-minima
